export const PermissionTypes = {
  LIST_PRODUCT: 'LIST_PRODUCT',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',

  LIST_CATEGORY: 'LIST_CATEGORY',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',

  LIST_COUPON: 'LIST_COUPON',
  CREATE_COUPON: 'CREATE_COUPON',
  UPDATE_COUPON: 'UPDATE_COUPON',
  DELETE_COUPON: 'DELETE_COUPON',

  EDIT_SETTINGS: 'EDIT_SETTINGS',
  EDIT_CHECKOUT_SETTINGS: 'EDIT_CHECKOUT_SETTINGS',
  EDIT_DOMAIN: 'EDIT_DOMAIN',
  EDIT_SUBDOMAIN: 'EDIT_SUBDOMAIN',

  LIST_VARIABLE: 'LIST_VARIABLE',
  CREATE_VARIABLE: 'CREATE_VARIABLE',
  UPDATE_VARIABLE: 'UPDATE_VARIABLE',
  DELETE_VARIABLE: 'DELETE_VARIABLE',

  EDIT_SERVER: 'EDIT_SERVER',
  DELETE_SERVER: 'DELETE_SERVER',
  CREATE_SERVER: 'CREATE_SERVER',
  LIST_SERVER: 'LIST_SERVER',

  LIST_MEMBERS: 'LIST_MEMBERS',
  INVITE_TEAM_MEMBER: 'INVITE_TEAM_MEMBER',
  REMOVE_TEAM_MEMBER: 'REMOVE_TEAM_MEMBER',
  EDIT_TEAM_MEMBER: 'EDIT_TEAM_MEMBER',

  VIEW_TEMPLATE: 'LIST_TEMPLATE',
  CREATE_TEMPLATE: 'CREATE_TEMPLATE',
  EDIT_TEMPLATE: 'EDIT_TEMPLATE',
  REMOVE_TEMPLATE: 'REMOVE_TEMPLATE',
} as const;

export type PermissionKey = keyof typeof PermissionTypes;
